name: Bump oxlint

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

env:
  OXLINT_PACKAGE_NAME: oxlint

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Bump oxlint rules
        run: |
          pnpm install
          pnpm update oxlint
          pnpm install
          pnpm run clone
          pnpm run generate # Generate rules from latest oxlint
          pnpm run test -u # Update test snapshots

      - uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'release: ${{ inputs.version }}'
          committer: Boshen <Boshen@users.noreply.github.com>
          author: Boshen <Boshen@users.noreply.github.com>
          branch: release
          branch-suffix: timestamp
          title: 'release: ${{ inputs.version }}'
          assignees: Boshen
          base: main
