name: Bump oxlint

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

env:
  OXLINT_PACKAGE_NAME: oxlint

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Bump oxlint rules
        run: |
          pnpm install
          pnpm update oxlint
          pnpm install
          pnpm run clone
          pnpm run generate # Generate rules from latest oxlint
          pnpm run test -u # Update test snapshots
          npm version ${{ inputs.version }} --no-git-tag-version

      - uses: peter-evans/create-pull-request@v7
        with:
          # bot account with PAT required for triggering workflow runs
          # See https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs
          token: ${{ secrets.OXC_BOT_PAT }}
          commit-message: 'release: v${{ inputs.version }}'
          committer: Boshen <Boshen@users.noreply.github.com>
          author: Boshen <Boshen@users.noreply.github.com>
          branch: release
          branch-suffix: timestamp
          title: 'release: v${{ inputs.version }}'
          assignees: Boshen
          base: main
