name: Bump oxlint

on:
  push:
    branches:
      - test-bump
  workflow_dispatch:
    inputs:
      version:
        required: false
        type: string
      issue-number:
        required: false
        type: string

permissions:
  pull-requests: write
  contents: write

env:
  OXLINT_PACKAGE_NAME: oxlint

jobs:
  bump-oxlint-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Bump oxlint rules
        run: |
          pnpm install
          pnpm update oxlint
          pnpm install
          pnpm run clone
          # Generate rules from latest oxlint
          pnpm run generate
          # Update test snapshots
          pnpm run test -u

      - uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Release ${{ inputs.version }}
          committer: Boshen <Boshen@users.noreply.github.com>
          author: Boshen <Boshen@users.noreply.github.com>
          branch: release
          branch-suffix: timestamp
          title: Release ${{ inputs.version }}
          body: From https://github.com/oxc-project/oxc/pull/${{ inputs.issue-number }}
          assignees: Boshen
          base: main
