name: Bump oxlint

on:
  pull_request:
    types:
      - labeled

permissions:
  pull-requests: write
  contents: write

jobs:
  bump-oxlint-rules:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'bump-oxlint'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: pnpm i

      - name: Bump oxlint rules
        run: |
          # Generate rules from latest oxlint
          pnpm run generate

          # Update test snapshots
          pnpm run test -u

          # Commit and push changes
          git config --global user.name "dependabot[bot]"
          git config --global user.email "49699333+dependabot[bot]@users.noreply.github.com"
          git commit -am "feat(oxlint): bump oxlint rules"
          git push
