name: Format (prettier)

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
      - 'renovate/**'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Format (prettier)
        run: npx prettier . --check
