name: Lint

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
      - 'renovate/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/pnpm

      - name: Run oxlint
        run: npx oxlint

      - name: Run eslint
        run: npx eslint --flag unstable_ts_config
