name: "Close stale issues and PRs"
on:
  schedule:
    - cron: "30 1 * * *"

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: "This issue is now considered as stale. Remove stale label or comment or this will be closed soon."
          stale-pr-message: "This PR is now considered as stale. Remove stale label or comment or this will be closed soon."
          exempt-pr-labels: "wip,keep"
