name: Type Check

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
      - 'renovate/**'

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/pnpm

      - name: Run eslint
        run: npx tsc --noEmit
